services:
    App\Auth\Entry\Http\Admin\Controller\User\UserAdmin:
        tags:
            - { name: sonata.admin, controller: App\Auth\Entry\Http\Admin\Controller\User\UserAdminController, model_class: App\Auth\Domain\User\User, manager_type: orm, label: User, group: Auth }
