security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Auth\Domain\User\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Auth\Domain\User\User
                property: email
        main:
            id: App\Auth\Infrastructure\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        token_invalidate_all_refresh:
            security: true
            pattern: ^/api/token/invalidate-all-refresh-tokens
            stateless: true
            user_checker: App\Auth\Infrastructure\Security\UserChecker
            custom_authenticators:
                - App\Auth\Infrastructure\Security\TokenAuthenticator

        token:
            security: false
            pattern: ^/api/token
            stateless: true

        client:
            security: true
            pattern: ^/api/client
            stateless: true
            user_checker: App\Auth\Infrastructure\Security\UserChecker
            custom_authenticators:
                - App\Auth\Infrastructure\Security\TokenAuthenticator

        admin:
            security: true
            pattern: ^/api/admin
            stateless: true
            user_checker: App\Auth\Infrastructure\Security\UserChecker
            custom_authenticators:
                - App\Auth\Infrastructure\Security\TokenAuthenticator

    access_control:
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/metrics, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: [ROLE_ADMIN] }
        - { path: ^/, roles: [ROLE_ADMIN] }
