security:
#    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Auth\Core\User\Domain\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Auth\Core\User\Domain\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: '^/'
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                failure_path: admin_login
                default_target_path: admin_home
                use_forward: true
                use_referer: true
            remember_me:
                secret: "%kernel.secret%"
                name: APP_ADMIN_REMEMBER_ME
                lifetime: 86400
                remember_me_parameter: _remember_me
            logout:
                path: admin_logout
                target: admin_login
    access_control:
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: ROLE_ADMIN }
        - { path: ^/$, roles: [ROLE_ADMIN] }
        - { path: ^/, roles: [ROLE_ADMIN] }
