security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Auth\Domain\User\User:
            algorithm: auto
    providers:
        api:
            id: App\Auth\Infrastructure\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_info:
            security: false
            pattern: ^/api/info
            stateless: true

        admin:
            security: true
            pattern: ^/api/admin
            stateless: true
            provider: api
            user_checker: App\Auth\Infrastructure\Security\AdminChecker
            custom_authenticators:
                - App\Auth\Infrastructure\Security\TokenAuthenticator

    access_control:
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/metrics, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: [ROLE_ADMIN] }
        - { path: ^/, roles: [ROLE_ADMIN] }
