version: "3.7"

networks:
  default:
    external: true
    name: app-network

services:
  nginx:
    container_name: app-nginx
    image: ${REGISTRY}/${NAMESPACE}/app-nginx:${IMAGE_TAG}
    restart: always
    ports:
      - "8080:80"

  app-php-fpm:
    image: ${REGISTRY}/${NAMESPACE}/app-app-php-fpm:${IMAGE_TAG}
    restart: always

  app-postgres-db:
    container_name: app-postgres-db
    volumes:
      - ./../pg_data:/var/lib/postgresql/data
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: application-db
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret

  rabbitmq:
    image: rabbitmq:management
    volumes:
      - ./../rabbit_data/:/var/lib/rabbitmq/mnesia/
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  app-metrics-sidecar:
    volumes:
      - ./../redis_metrics:/data
    image: redis:alpine
    restart: always

  redis:
    image: redis:5
    volumes:
      - ./../redis_app:/data
    restart: always
    environment:
      REDIS_PASSWORD: none
