version: "3.7"

networks:
  default:
    name: app-network
    external: true

services:
  app-nginx:
    build:
      context: docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./:/app
    labels:
      - traefik.http.routers.pf_profile.rule=Host(`app.localhost`)
      - traefik.http.routers.pf_profile.entrypoints=http
      - traefik.http.routers.pf_profile.middlewares=redirect
      - traefik.http.middlewares.redirect.redirectscheme.scheme=http

  app-php-fpm:
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./:/app
      - app_cache:/var/cache/app
      - app_log:/var/log/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=app" # Необходимо назвать в Languages & Frameworks -> PHP -> Servers новый сервер как "app"
      XDEBUG_SESSION: "1"
      XDEBUG_REMOTE_CONNECT_BACK: 0
      XDEBUG_MODE: "debug"

volumes:
  app_cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  app_log:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
