version: "3.7"

networks:
  default:
    name: internal-network

services:
  nginx:
    image: ${REGISTRY}/skeleton-nginx:${IMAGE_TAG}
    restart: always

  app-php-fpm:
    image: ${REGISTRY}/skeleton-php-fpm:${IMAGE_TAG}
    restart: always

  app-php-cli:
    image: ${REGISTRY}/skeleton-php-cli:${IMAGE_TAG}

  app-postgres-db:
    volumes:
      - ./database:/var/lib/postgresql/data
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: application-db
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret

  app-metrics-sidecar:
    image: redis:alpine
    restart: always

  redis:
    image: redis:5
    restart: always
    environment:
      REDIS_PASSWORD: none

