version: "3.7"

networks:
  internal-network:

services:
  nginx:
    build:
      context: docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./:/app
    networks:
      - internal-network

  app-php-fpm:
    build:
      context: docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./:/app
      - app_cache:/var/cache/app
      - app_log:/var/log/app
    networks:
      - internal-network

  app-php-cli:
    build:
      context: docker
      dockerfile: development/php-cli/Dockerfile
    volumes:
      - ./:/app
      - app_cache:/var/cache/app
      - app_log:/var/log/app
    networks:
      - internal-network

  app-postgres-db:
    volumes:
      - db:/var/lib/postgresql/data
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: application-db
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret
    networks:
      - internal-network

volumes:
  db:
  app_cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  app_log:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
