version: "3.7"

networks:
  default:
    name: internal-network

services:
  nginx:
    container_name: app-nginx
    image: ${REGISTRY}/app-nginx:${IMAGE_TAG}
    restart: always
    ports:
      - "8080:80"

  app-php-fpm:
    image: ${REGISTRY}/app-app-php-fpm:${IMAGE_TAG}
    restart: always

  app-php-cli:
    image: ${REGISTRY}/app-app-php-cli:${IMAGE_TAG}

  app-postgres-db:
    container_name: app-postgres-db
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: application-db
      POSTGRES_USER: default
      POSTGRES_PASSWORD: secret

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  app-metrics-sidecar:
    image: redis:alpine
    restart: always

  redis:
    image: redis:5
    restart: always
    environment:
      REDIS_PASSWORD: none
