services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags:
                name: doctrine.event_subscriber
                connection: default

    App\Common\:
        resource: '../'
        exclude:
            - '../config'

    App\Common\Entry\Http\:
        resource: '../Entry/Http/'
        tags: [ 'controller.service_arguments' ]

    App\Common\Service\Core\Flusher: ~

    App\Common\Service\Core\EventDispatcher:
        class: App\Common\Service\Dispatcher\MessengerEventDispatcher

    App\Common\EventSubscriber\Exception\HttpExceptionSubscriber:
        arguments:
            $env: '%env(APP_ENV)%'
            $debug: '%env(LOCAL_TEST)%'

    Symfony\Component\Serializer\SerializerInterface:
        factory: [ 'App\Common\Container\SerializerFactory', 'create' ]

    App\Common\Service\Metrics\Adapters\Redis\Config:
        arguments:
            $host: '%env(METRICS_SIDECAR_HOST)%'
            $namespace: 'app'

    App\Common\Service\Metrics\MetricsGuard:
        arguments:
            $appEnv: '%env(APP_ENV)%'
            $prometheusHost: '%env(PROMETHEUS_HOST)%'

    app.menu_builder:
        class: App\Common\Entry\Http\Admin\Menu\MainMenuBuilder
        arguments:
            $factory: "@knp_menu.factory"
        tags:
            - { name: knp_menu.menu_builder, method: buildMenu, alias: ec.main }

    App\Common\Entry\Http\Admin\Menu\SectionBuilderFactory:
        arguments:
            - !tagged_iterator app.section_builder


    App\Common\Entry\Http\Admin\Grid\FieldType\BooleanType:
        tags:
            - { name: sylius.grid_field, type: boolean }

    App\Common\Entry\Http\Admin\Grid\FieldType\NullableStringType:
        tags:
            - { name: sylius.grid_field, type: nullable_string }

    App\Common\Entry\Http\Admin\Grid\Filter\TimestampFilter:
        tags:
            - { name: 'sylius.grid_filter', type: 'timestamp', form_type: App\Common\Entry\Http\Admin\Form\Filter\TimestampType }

    App\Common\Entry\Http\Admin\Grid\Filter\NumberFilter:
        tags:
            - { name: 'sylius.grid_filter', type: 'number', form_type: App\Common\Entry\Http\Admin\Form\Filter\NumberType }

    App\Common\Entry\Http\Admin\Grid\Filter\Select2Filter:
        tags:
            - { name: 'sylius.grid_filter', type: 'select2', form_type: App\Common\Entry\Http\Admin\Form\Filter\Select2Type }

    App\Common\Entry\Http\Admin\Grid\Filter\IntegerFilter:
        tags:
            - { name: 'sylius.grid_filter', type: 'int', form_type: App\Common\Entry\Http\Admin\Form\Filter\IntegerFilterType }
