services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Doctrine\Common\EventSubscriber:
            tags:
                name: doctrine.event_subscriber
                connection: default

    App\Common\:
        resource: '../'
        exclude:
            - '../config'

    App\Common\Entry\Http\:
        resource: '../Entry/Http/'
        tags: [ 'controller.service_arguments' ]

    App\Common\Service\Core\Flusher: ~

    App\Common\Service\Core\EventDispatcher:
        class: App\Common\Service\Dispatcher\MessengerEventDispatcher

    App\Common\EventSubscriber\Exception\HttpExceptionSubscriber:
        arguments:
            $env: '%env(APP_ENV)%'
            $debug: '%env(LOCAL_TEST)%'

    Symfony\Component\Serializer\SerializerInterface:
        factory: [ 'App\Common\Container\SerializerFactory', 'create' ]

    App\Common\Service\Metrics\Adapters\Redis\Config:
        arguments:
            $host: '%env(METRICS_SIDECAR_HOST)%'
            $namespace: 'app'

    App\Common\Service\Metrics\MetricsGuard:
        arguments:
            $prometheusHost: '%env(PROMETHEUS_HOST)%'

    app.menu_builder:
        class: App\Common\Entry\Http\Admin\Menu\MainMenuBuilder
        arguments:
            $factory: "@knp_menu.factory"
