parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client

    Redis:
        # you can also use \RedisArray, \RedisCluster or \Predis\Client classes
        class: Redis
        calls:
            -   connect:
                    - '%env(REDIS_HOST)%'
                    - '%env(int:REDIS_PORT)%'
            -   auth:
                    - '%env(REDIS_PASSWORD)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'
            # you can optionally pass an array of options. The only option is 'prefix',
            # which defines the prefix to use for the keys to avoid collision on the Redis server
            - { prefix: '%kernel.project_dir%' }
