services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Functional\:
        resource: '../tests/Functional/**/*Fixture.php'
        tags: ['doctrine.fixture.orm']

    App\Tests\Integration\:
        resource: '../tests/Integration/**/*Fixture.php'
        tags: ['doctrine.fixture.orm']

    App\Tests\Acceptance\:
        resource: '../tests/Acceptance/**/*Fixture.php'
        tags: ['doctrine.fixture.orm']
