parameters:
    locale: 'ru'
    path.src: '%kernel.project_dir%/src'
    path.root: '%kernel.project_dir%'
    .container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Monolog\Processor\PsrLogMessageProcessor:
        tags: { name: monolog.processor, handler: sentry }

    GuzzleHttp\ClientInterface:
        class: GuzzleHttp\Client

    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    Psr\Container\ContainerInterface: '@service_container'

    security.authorization_checker:
        class: Symfony\Component\Security\Core\Authorization\AuthorizationChecker
        public: true

    Redis:
        # you can also use \RedisArray, \RedisCluster or \Predis\Client classes
        class: Redis
        calls:
            -   connect:
                    - '%env(REDIS_HOST)%'
                    - '%env(int:REDIS_PORT)%'
            -   auth:
                    - '%env(REDIS_PASSWORD)%'

    Symfony\Component\RateLimiter\RateLimiterFactory $anonymousApiCommon: '@limiter.anonymous_api_common'
    Symfony\Component\RateLimiter\RateLimiterFactory $authenticatedApiCommon: '@limiter.authenticated_api_common'
