services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Integration\:
        public: true
        resource: '../tests/Integration/**/*Fixture.php'

    App\Tests\Functional\:
        public: true
        resource: '../tests/Functional/**/*Fixture.php'

    App\Common\EventListener\Exception\HttpExceptionSubscriber:
        public: true
        arguments:
            $env: '%env(APP_ENV)%'
            $debug: '%env(LOCAL_TEST)%'
