---
#1. Установка Nginx:
- name: Install Nginx
  become: yes
  apt:
    name: nginx
    state: present

#2. Создание директорий для хранения конфигурационных файлов:
- name: Create directory for nginx configuration
  become: yes
  file:
    path: /etc/nginx/sites-available
    state: directory

- name: Create directory for nginx enabled sites
  become: yes
  file:
    path: /etc/nginx/sites-enabled
    state: directory

#3. Копирование файла конфигурации на сервер:
- name: Copy nginx config file
  become: yes
  vars:
    server_name: 111.111.111.111
  template:
    src=templates/app.nginx.conf
    dest=/etc/nginx/sites-available/app

#4. Создание символической ссылки на файл конфигурации:
- name: Create a symbolic link to Nginx config file
  become: yes
  file:
    src: /etc/nginx/sites-available/app
    dest: /etc/nginx/sites-enabled/app
    state: link

#5. Перезапуск сервиса Nginx:
- name: Restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted
