sylius_resource:
    resources:
        app.user:
            templates: admin/layout/crud
            driver: doctrine/orm
            classes:
                model: App\Auth\Core\User\Domain\User
                controller: App\Auth\Entry\Http\Admin\User\UserController
