services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Auth\Security\JWT:
        public: true

    App\Auth\Security\JwtTokenizer:
        public: true

    App\Auth\Core\User\Application\UseCase\ChangePassword\Handler:
        public: true

    App\Auth\Core\User\Application\UseCase\Delete\Handler:
        public: true

    App\Auth\Core\User\Application\UseCase\Edit\Handler:
        public: true
