/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const getActiveHead: typeof import('unhead')['getActiveHead']
  const useHead: typeof import('unhead')['useHead']
  const useHeadSafe: typeof import('unhead')['useHeadSafe']
  const useSeoMeta: typeof import('unhead')['useSeoMeta']
  const useServerHead: typeof import('unhead')['useServerHead']
  const useServerHeadSafe: typeof import('unhead')['useServerHeadSafe']
  const useServerSeoMeta: typeof import('unhead')['useServerSeoMeta']
}
