serve:
	yarn dev

linters:
	yarn type-check

install:
	yarn install

build:
	yarn build

build-only:
	yarn build-only

preview:
	yarn preview

test:
	yarn test:unit

cc:
	yarn cache clean

smart-grid-regenerate:
	node smart-grid-settings.js
	yarn migrate-sass
