name: Testing

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Docker Compose
      run: |
        sudo apt-get remove docker-compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Up-Test-Down
      run: |
        make test-ci
