app_user:
    resource: |
        path: users
        alias: app.user
        only: ['index', 'show']
        redirect: show
        grid: app_user
        vars:
            all:
                templates:
                    show: "admin/auth/user/show.html.twig"
            index:
                icon: 'icon users'
    type: sylius.resource
